spring:
  datasource:
    url: jdbc:mysql://123.57.78.6:3306/campus?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234


minio:
  accesskey: e07e56d6258c
  secretkey: 26bd27eac5a0